[tool.pytest.ini_options]
asyncio_default_fixture_loop_scope = "function"
asyncio_mode="auto"
filterwarnings = "ignore::DeprecationWarning"

[tool.mypy]
disable_error_code = ["import-untyped"]

pythonpath = [
  "."]
